### ISSUE TITLE
Test failures due to mismatched line endings, `\r\n` vs `\n`

### ISSUE THREAD

**Issue by aSemy** [JetBrains-Research/reflekt#100]
I've checked out master and when I run the tests I get failures due to mismatched line endings.

![image](https://user-images.githubusercontent.com/897017/159095886-3376ca01-da61-48bd-8847-a60b8c92aea6.png)

"Contents have differences only in line separators".

I've tried implementing a function to normalize the line endings to `\n`

```kotlin
/**
 * Read all lines in a file, with line-endings normalized to `\n`. The result is [trim]-ed.
 *
 * This helps ensure consistent test results across Windows and Unix platforms.
 */
fun File.readTextNormalized(): String = useLines(Charsets.UTF_8) { it.joinToString("\n").trim() }
```

However this doesn't resolve the issue, and for some reason the 'actual' isn't loaded correctly

![image](https://user-images.githubusercontent.com/897017/159096430-5bf0c58c-249f-40cc-b55a-6f37988a0f5b.png)

---

I see that in `.editorconfig` the line endings are specified as `lf`, but because there's no `.gitattributes` file, very few of the files are formatted as `lf`.

The fix is probably to add `.gitattributes` and reformat all files to have `lf` endings.

**Comment by elena-lyulina** [comment]
Yes, you're right, thanks for noticing it 
I'll check your PR and close the issue after merging
we really appreciate your help :)
