### ISSUE TITLE
Add ktlint in the project

### ISSUE THREAD

**Issue by nbirillo** [JetBrains-Research/reflekt#65]
Add ktlint and fix all code quality issues if it is necessary

**Comment by akuleshov7** [comment]
Phaze#1 done in #81

**Comment by akuleshov7** [comment]
@nbirillo could you please link the PR to this issue,I don't have an access :(

**Comment by elena-lyulina** [comment]
@akuleshov7 thanks a lot for your help :)
I have merged everything into the [master](https://github.com/JetBrains-Research/reflekt/tree/master) branch.
`detekt` gradle task is commented out for now, it would be great if you could continue working on it

**Comment by akuleshov7** [comment]
@elena-lyulina hi, Lena, I will finish the detekt this week. Detekt automated estimations on fixing everything is more than 24 hours 😂

**Comment by akuleshov7** [comment]
@elena-lyulina @nbirillo pls check:
https://github.com/JetBrains-Research/reflekt/pull/85
