### ISSUE TITLE
Update and correct Gradle config

### ISSUE THREAD

**Issue by aSemy** [JetBrains-Research/reflekt#99]
Hi, I've been looking at using this project and I see that the Gradle config could be improved. I like fixing Gradle, so I'm happy to make a PR.

Here's a non-complete list:

1. remove unused or unrequired plugins & dependencies
  * `com.github.gmazzo.buildconfig`, unused

I'll look into making some additional improvements, like using the Kover for code coverage.

**Comment by CommanderTvis** [comment]
(1) is already done in #108

**Comment by CommanderTvis** [comment]
By the way, I don't think kosogor should be removed, I don't see any reasons its functionality should be written manually in the build files.

**Comment by CommanderTvis** [comment]
@aSemy edited your list to remove things that are already done.
